Repository amp-buildpacks/cairo, pull requests merged in 2024-06, with the labels that each got.

#7 Bump pipeline from 0.0.0 to 1.39.0
  .github/CODEOWNERS
  .github/labels.yml
  .github/pipeline-version
  .github/release-drafter.yml
  .github/workflows/pb-create-package.yml
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-pipeline.yml
  .github/workflows/pb-update-procfile.yml
  .github/workflows/pb-update-scarb.yml
  .github/workflows/pb-update-starknet.yml
Labels: semver:patch, type:task

#8 upgrade scarb and startnet version
  buildpack.toml
  config.toml
  package.toml
Labels: semver:major, type:enhancement

#9 Bump pipeline from 1.39.0 to 1.39.0
  .gitignore
Labels: semver:patch, type:task

#11 Bump ghcr.io/amp-buildpacks/starknet from 1.0.0 to 1.0.1
  buildpack.toml
  package.toml
Labels: semver:patch, type:dependency-upgrade

#13 Bump ghcr.io/amp-buildpacks/starknet from 1.0.1 to 1.0.2
  buildpack.toml
  package.toml
Labels: semver:patch, type:dependency-upgrade
